"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const db_1 = require("./db");
exports.default = db_1.DB;
var db_2 = require("./db");
exports.DB = db_2.DB;
exports.FirebaseBoolean = db_2.FirebaseBoolean;
var database_1 = require("@firebase/database");
exports.DataSnapshot = database_1.DataSnapshot;
exports.Query = database_1.Query;
exports.Reference = database_1.Reference;
exports.Database = database_1.Database;
